/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htmlparser.view;

import htlmparser.control.Controller;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Tom
 */
public class View extends javax.swing.JFrame {
    
    private Controller controller;
    private boolean highlightChecked;
    
    public View(Controller c) {
        initComponents();
        
        this.controller = c;
        
        this.teamHighlight.setVisible(false);
        this.highlightChecked = false;
        this.teamsBox.setVisible(false);
        this.saveButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlField = new javax.swing.JTextField();
        urlSubmit = new javax.swing.JButton();
        teamHighlight = new javax.swing.JCheckBox();
        teamsBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        urlField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urlField.setText("Enter URL");
        urlField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlFieldMouseClicked(evt);
            }
        });

        urlSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        urlSubmit.setText("OK");
        urlSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlSubmitActionPerformed(evt);
            }
        });

        teamHighlight.setText("Highlight a team");
        teamHighlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamHighlightActionPerformed(evt);
            }
        });

        teamsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty" }));
        teamsBox.setFocusable(false);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamHighlight)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urlSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(teamsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(saveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(urlField)
                    .addComponent(urlSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(teamHighlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teamsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlSubmitActionPerformed
        this.controller.getURL(this.urlField.getText());
    }//GEN-LAST:event_urlSubmitActionPerformed

    private void urlFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlFieldMouseClicked
        this.urlField.setText("");
    }//GEN-LAST:event_urlFieldMouseClicked

    private void teamHighlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamHighlightActionPerformed
        if (this.highlightChecked) {
            this.highlightChecked = false;
            this.teamsBox.setVisible(false);
        }
        else {
            this.highlightChecked = true;
            this.teamsBox.setVisible(true);
        }
    }//GEN-LAST:event_teamHighlightActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        this.controller.saveFile();
        
    }//GEN-LAST:event_saveButtonActionPerformed
    
    public void urlSuccess() {
        this.teamHighlight.setVisible(true);
        this.saveButton.setVisible(true);
    }
    
    public void fillTeams(ArrayList<String> teams) {
        ComboBoxData model = new ComboBoxData(teams);
        this.teamsBox.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox teamHighlight;
    private javax.swing.JComboBox teamsBox;
    private javax.swing.JTextField urlField;
    private javax.swing.JButton urlSubmit;
    // End of variables declaration//GEN-END:variables
}
