/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htmlparser.view;

import htlmparser.control.Controller;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/**
 *
 * @author Tom
 */
public class View extends javax.swing.JFrame {
    
    private Controller controller;
    private JFileChooser dirChoose;
    
    public View(Controller c) {
        initComponents();
        
        this.controller = c;
        
        this.teamHighlight.setVisible(false);
        this.teamsBox.setVisible(false);
        this.saveButton.setVisible(false);
        this.color1.setVisible(false);
        this.color2.setVisible(false);
        this.font.setVisible(false);
        this.colorsLabel.setVisible(false);
        this.color1Label.setVisible(false);
        this.color2Label.setVisible(false);
        this.color3Label.setVisible(false);
        this.excelBox.setVisible(false);
        this.pdfBox.setVisible(false);
        this.matchBox.setVisible(false);
        this.matchCheck.setVisible(false);
        this.competitionLabel.setVisible(false);
        this.compName.setVisible(false);
        
        this.teamsBox.setEnabled(false);
        this.matchBox.setEnabled(false);
        this.saveButton.setEnabled(false);
        
        this.dirChoose = new JFileChooser(new File("."));
        this.dirChoose.setDialogTitle("Vyber místo pro uložení");
        this.dirChoose.setAcceptAllFileFilterUsed(false);
        this.dirChoose.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlField = new javax.swing.JTextField();
        urlSubmit = new javax.swing.JButton();
        teamHighlight = new javax.swing.JCheckBox();
        teamsBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        color1 = new javax.swing.JButton();
        color2 = new javax.swing.JButton();
        font = new javax.swing.JButton();
        colorsLabel = new javax.swing.JLabel();
        color1Label = new javax.swing.JLabel();
        color2Label = new javax.swing.JLabel();
        color3Label = new javax.swing.JLabel();
        excelBox = new javax.swing.JCheckBox();
        pdfBox = new javax.swing.JCheckBox();
        matchCheck = new javax.swing.JCheckBox();
        matchBox = new javax.swing.JComboBox();
        copyrightLabel = new javax.swing.JLabel();
        competitionLabel = new javax.swing.JLabel();
        compName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabulky soutěží a zápasů");
        setResizable(false);

        urlField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urlField.setText("Klikni a vlož odkaz na tabulku soutěže z fotbal.cz");
        urlField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlFieldMouseClicked(evt);
            }
        });

        urlSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        urlSubmit.setText("OK");
        urlSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlSubmitActionPerformed(evt);
            }
        });

        teamHighlight.setText("Zvýraznit tým");
        teamHighlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamHighlightActionPerformed(evt);
            }
        });

        teamsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Žádný tým nenalezen" }));
        teamsBox.setFocusable(false);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setText("ULOŽIT");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        color1.setText("Střídavé pozadí");
        color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color1ActionPerformed(evt);
            }
        });

        color2.setText("Pozadí názvů sloupců");
        color2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color2ActionPerformed(evt);
            }
        });

        font.setText("Písmo názvů sloupců");
        font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontActionPerformed(evt);
            }
        });

        colorsLabel.setText("Vyber barvy:");

        color1Label.setBackground(new java.awt.Color(197, 217, 241));
        color1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color1Label.setOpaque(true);

        color2Label.setBackground(new java.awt.Color(83, 141, 213));
        color2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color2Label.setOpaque(true);

        color3Label.setBackground(new java.awt.Color(255, 255, 255));
        color3Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color3Label.setOpaque(true);

        excelBox.setText("Uložit jako tabulku v Excelu");
        excelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBoxActionPerformed(evt);
            }
        });

        pdfBox.setText("Uložit jako PDF");
        pdfBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfBoxActionPerformed(evt);
            }
        });

        matchCheck.setText("Vytvořit tabulku zápasů pro konkrétní tým");
        matchCheck.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                matchCheckItemStateChanged(evt);
            }
        });

        matchBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Žádný tým nenalezen" }));

        copyrightLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        copyrightLabel.setText("Copyright © Tomáš Panoc");

        competitionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        competitionLabel.setText("Soutěž:");

        compName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        compName.setForeground(new java.awt.Color(0, 51, 255));
        compName.setText("Competition name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(excelBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pdfBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamHighlight)
                            .addComponent(matchCheck)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(teamsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(matchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(colorsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(font)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(color1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(color2)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(color1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(color2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(color3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(competitionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(urlSubmit)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(copyrightLabel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(urlSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(urlField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(competitionLabel)
                    .addComponent(compName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamHighlight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teamsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(matchCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matchBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color1)
                            .addComponent(color1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(color2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(font))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(color2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(color3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excelBox)
                    .addComponent(pdfBox)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(copyrightLabel))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlSubmitActionPerformed
        this.controller.setURL(this.urlField.getText());
    }//GEN-LAST:event_urlSubmitActionPerformed

    private void urlFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlFieldMouseClicked
        this.urlField.setText("");
    }//GEN-LAST:event_urlFieldMouseClicked

    private void teamHighlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamHighlightActionPerformed
        if (this.teamHighlight.isSelected()) {
            this.teamsBox.setEnabled(true);
        }
        else {
            this.teamsBox.setEnabled(false);
        }
    }//GEN-LAST:event_teamHighlightActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        String selected = null;
        String matches = null;
        
        if (this.teamHighlight.isSelected()) {
            
            selected = (String) this.teamsBox.getSelectedItem();
            
        }
        
        if (this.matchCheck.isSelected()) {
            
            matches = (String) this.matchBox.getSelectedItem();
            
        }
        
        if (this.excelBox.isSelected() && this.pdfBox.isSelected()) {
            this.dirChoose.showOpenDialog(this);
            File dir = this.dirChoose.getSelectedFile();
            System.out.println(dir.getPath());
            this.controller.saveFile(selected, true, true, matches, dir.getPath());
        }
        else if (this.excelBox.isSelected() && !this.pdfBox.isSelected()) {
            this.dirChoose.showOpenDialog(this);
            File dir = this.dirChoose.getSelectedFile();
            System.out.println(dir.getPath());
            this.controller.saveFile(selected, true, false, matches, dir.getPath());
        }
        else if (!this.excelBox.isSelected() && this.pdfBox.isSelected()) {
            this.dirChoose.showOpenDialog(this);
            File dir = this.dirChoose.getSelectedFile();
            System.out.println(dir.getPath());
            this.controller.saveFile(selected, false, true, matches, dir.getPath());
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color1ActionPerformed
        
        Color c = JColorChooser.showDialog(null, "Vyber barvu", this.getForeground());
        if (c != null) {
            this.controller.setColor1(c);
            this.color1Label.setBackground(c);
        }
        
    }//GEN-LAST:event_color1ActionPerformed

    private void color2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color2ActionPerformed
        
        Color c = JColorChooser.showDialog(null, "Vyber barvu", this.getForeground());
        if (c != null) {
            this.controller.setColor2(c);
            this.color2Label.setBackground(c);
        }
        
    }//GEN-LAST:event_color2ActionPerformed

    private void fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontActionPerformed
        
        Color c = JColorChooser.showDialog(null, "Choose a Color", this.getForeground());
        if (c != null) {
            this.controller.setColor3(c);
            this.color3Label.setBackground(c);
        }
        
    }//GEN-LAST:event_fontActionPerformed

    private void excelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBoxActionPerformed
        if (this.excelBox.isSelected()) {
            this.saveButton.setEnabled(true);
        }
        else if(!this.excelBox.isSelected() && !this.pdfBox.isSelected()) {
            this.saveButton.setEnabled(false);
        }
    }//GEN-LAST:event_excelBoxActionPerformed

    private void pdfBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfBoxActionPerformed
        if (this.pdfBox.isSelected()) {
            this.saveButton.setEnabled(true);
        }
        else if(!this.pdfBox.isSelected() && !this.excelBox.isSelected()) {
            this.saveButton.setEnabled(false);
        }
    }//GEN-LAST:event_pdfBoxActionPerformed

    private void matchCheckItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_matchCheckItemStateChanged
        this.matchBox.setEnabled(!this.matchBox.isEnabled());
    }//GEN-LAST:event_matchCheckItemStateChanged
    
    public void urlSuccess() {
        this.teamHighlight.setVisible(true);
        this.teamsBox.setVisible(true);
        this.saveButton.setVisible(true);
        this.color1.setVisible(true);
        this.color2.setVisible(true);
        this.font.setVisible(true);
        this.colorsLabel.setVisible(true);
        this.color1Label.setVisible(true);
        this.color2Label.setVisible(true);
        this.color3Label.setVisible(true);
        this.excelBox.setVisible(true);
        this.pdfBox.setVisible(true);
        this.matchBox.setVisible(true);
        this.matchCheck.setVisible(true);
        this.competitionLabel.setVisible(true);
        this.compName.setVisible(true);
    }
    
    public void displayFileName(String filename) {
        this.compName.setText(filename);
    }
    
    public void fillTeams(ArrayList<String> teams) {
        ComboBoxData model = new ComboBoxData(teams);
        ComboBoxData modelmatches = new ComboBoxData (teams);
        this.teamsBox.setModel(model);
        this.matchBox.setModel(modelmatches);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton color1;
    private javax.swing.JLabel color1Label;
    private javax.swing.JButton color2;
    private javax.swing.JLabel color2Label;
    private javax.swing.JLabel color3Label;
    private javax.swing.JLabel colorsLabel;
    private javax.swing.JLabel compName;
    private javax.swing.JLabel competitionLabel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JCheckBox excelBox;
    private javax.swing.JButton font;
    private javax.swing.JComboBox matchBox;
    private javax.swing.JCheckBox matchCheck;
    private javax.swing.JCheckBox pdfBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox teamHighlight;
    private javax.swing.JComboBox teamsBox;
    private javax.swing.JTextField urlField;
    private javax.swing.JButton urlSubmit;
    // End of variables declaration//GEN-END:variables
}
