/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htmlparser.view;

import htlmparser.control.Controller;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;

/**
 *
 * @author Tom
 */
public class View extends javax.swing.JFrame {
    
    private Controller controller;
    
    public View(Controller c) {
        initComponents();
        
        this.controller = c;
        
        this.teamHighlight.setVisible(false);
        this.teamsBox.setVisible(false);
        this.saveButton.setVisible(false);
        this.color1.setVisible(false);
        this.color2.setVisible(false);
        this.font.setVisible(false);
        this.colorsLabel.setVisible(false);
        this.color1Label.setVisible(false);
        this.color2Label.setVisible(false);
        this.color3Label.setVisible(false);
        this.excelBox.setVisible(false);
        this.pdfBox.setVisible(false);
        
        this.teamsBox.setEnabled(false);
        this.saveButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        urlField = new javax.swing.JTextField();
        urlSubmit = new javax.swing.JButton();
        teamHighlight = new javax.swing.JCheckBox();
        teamsBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        color1 = new javax.swing.JButton();
        color2 = new javax.swing.JButton();
        font = new javax.swing.JButton();
        colorsLabel = new javax.swing.JLabel();
        color1Label = new javax.swing.JLabel();
        color2Label = new javax.swing.JLabel();
        color3Label = new javax.swing.JLabel();
        excelBox = new javax.swing.JCheckBox();
        pdfBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        urlField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        urlField.setText("Enter URL");
        urlField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlFieldMouseClicked(evt);
            }
        });

        urlSubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        urlSubmit.setText("OK");
        urlSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlSubmitActionPerformed(evt);
            }
        });

        teamHighlight.setText("Highlight a team");
        teamHighlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamHighlightActionPerformed(evt);
            }
        });

        teamsBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empty" }));
        teamsBox.setFocusable(false);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        color1.setText("Odd row");
        color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color1ActionPerformed(evt);
            }
        });

        color2.setText("Titles background");
        color2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color2ActionPerformed(evt);
            }
        });

        font.setText("Titles font");
        font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontActionPerformed(evt);
            }
        });

        colorsLabel.setText("Choose colors:");

        color1Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color1Label.setOpaque(true);

        color2Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color2Label.setOpaque(true);

        color3Label.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        color3Label.setOpaque(true);

        excelBox.setText("Save as Excel");
        excelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBoxActionPerformed(evt);
            }
        });

        pdfBox.setText("Save as PDF");
        pdfBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(teamsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(font)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(color1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(color2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(color3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(urlField, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(urlSubmit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(teamHighlight)
                                .addGap(117, 117, 117)
                                .addComponent(colorsLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(excelBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pdfBox)
                                .addGap(18, 18, 18)
                                .addComponent(saveButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(urlField)
                    .addComponent(urlSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teamHighlight)
                    .addComponent(colorsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color1)
                            .addComponent(color1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(color2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(font))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(color2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(color3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excelBox)
                    .addComponent(pdfBox)
                    .addComponent(saveButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urlSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlSubmitActionPerformed
        this.controller.getURL(this.urlField.getText());
    }//GEN-LAST:event_urlSubmitActionPerformed

    private void urlFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlFieldMouseClicked
        this.urlField.setText("");
    }//GEN-LAST:event_urlFieldMouseClicked

    private void teamHighlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamHighlightActionPerformed
        if (this.teamHighlight.isSelected()) {
            this.teamsBox.setEnabled(true);
        }
        else {
            this.teamsBox.setEnabled(false);
        }
    }//GEN-LAST:event_teamHighlightActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        String selected = null;
        
        if (this.teamHighlight.isSelected()) {
            
            selected = (String) this.teamsBox.getSelectedItem();
            
        }
        
        if (this.excelBox.isSelected() && this.pdfBox.isSelected()) {
            this.controller.saveFile(selected, true, true);
        }
        else if (this.excelBox.isSelected() && !this.pdfBox.isSelected()) {
            this.controller.saveFile(selected, true, false);
        }
        else if (!this.excelBox.isSelected() && this.pdfBox.isSelected()) {
            this.controller.saveFile(selected, false, true);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color1ActionPerformed
        
        Color c = JColorChooser.showDialog(null, "Choose a Color", this.getForeground());
        if (c != null) {
            this.controller.setColor1(c);
            this.color1Label.setBackground(c);
        }
        
    }//GEN-LAST:event_color1ActionPerformed

    private void color2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color2ActionPerformed
        
        Color c = JColorChooser.showDialog(null, "Choose a Color", this.getForeground());
        if (c != null) {
            this.controller.setColor2(c);
            this.color2Label.setBackground(c);
        }
        
    }//GEN-LAST:event_color2ActionPerformed

    private void fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontActionPerformed
        
        Color c = JColorChooser.showDialog(null, "Choose a Color", this.getForeground());
        if (c != null) {
            this.controller.setColor3(c);
            this.color3Label.setBackground(c);
        }
        
    }//GEN-LAST:event_fontActionPerformed

    private void excelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBoxActionPerformed
        if (this.excelBox.isSelected()) {
            this.saveButton.setEnabled(true);
        }
        else if(!this.excelBox.isSelected() && !this.pdfBox.isSelected()) {
            this.saveButton.setEnabled(false);
        }
    }//GEN-LAST:event_excelBoxActionPerformed

    private void pdfBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfBoxActionPerformed
        if (this.pdfBox.isSelected()) {
            this.saveButton.setEnabled(true);
        }
        else if(!this.pdfBox.isSelected() && !this.excelBox.isSelected()) {
            this.saveButton.setEnabled(false);
        }
    }//GEN-LAST:event_pdfBoxActionPerformed
    
    public void urlSuccess() {
        this.teamHighlight.setVisible(true);
        this.teamsBox.setVisible(true);
        this.saveButton.setVisible(true);
        this.color1.setVisible(true);
        this.color2.setVisible(true);
        this.font.setVisible(true);
        this.colorsLabel.setVisible(true);
        this.color1Label.setVisible(true);
        this.color2Label.setVisible(true);
        this.color3Label.setVisible(true);
        this.excelBox.setVisible(true);
        this.pdfBox.setVisible(true);
    }
    
    public void fillTeams(ArrayList<String> teams) {
        ComboBoxData model = new ComboBoxData(teams);
        this.teamsBox.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton color1;
    private javax.swing.JLabel color1Label;
    private javax.swing.JButton color2;
    private javax.swing.JLabel color2Label;
    private javax.swing.JLabel color3Label;
    private javax.swing.JLabel colorsLabel;
    private javax.swing.JCheckBox excelBox;
    private javax.swing.JButton font;
    private javax.swing.JCheckBox pdfBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox teamHighlight;
    private javax.swing.JComboBox teamsBox;
    private javax.swing.JTextField urlField;
    private javax.swing.JButton urlSubmit;
    // End of variables declaration//GEN-END:variables
}
